stages:
  - lint
  - test

variables:
  GOPATH: /go

cache:
  key:
    files:
      - go.sum
  paths:
    - /go/pkg/mod/

vet:
  stage: lint
  image: golang:1.22-bookworm
  script:
    - go vet ./...

fmt-check:
  stage: lint
  image: golang:1.22-bookworm
  script:
    - test -z "$(gofmt -l . | grep -v '.pb.go' || true)"

test:
  stage: test
  image: golang:1.22-bookworm
  timeout: 60m
  script:
    - go test -timeout 60m ./...
